apiVersion: v1
kind: ConfigMap
metadata:
  name: static-nodepools-config
  namespace: default
data:
  reservations: |
    - "tpu7x-test"
  nodepoolConfig: |
    machineType: "tpu7x-standard-4t"
    accelerator: "tpu7x"
    topology: "4x4x4"
    nodeCount: 16
    nodeLabels:
      google.com/nodepool-manager: tpu-provisioner
    shieldedIntegrityMonitoring: true
    maxPodsPerNode: 15
    enableAutorepair: true
    placementPolicy: "tpu-provisioner-4x4x4"
