apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: lws-7x
  labels:
    tpu-provisioner.cloud.google.com/slice-autoprovisioning: async
  annotations:
    # Optional: Manually select specific slice partitions
    # Format: [{"leader": ["partition-id"], "workers": [["partition-id", ...]]}]
    tpu-provisioner.cloud.google.com/slice-selection: |
      [
        {
          "leader": ["a000t4x4x4"],
          "workers": [["b000t4x4x4", "c000t4x4x4"]]
        }
      ]
spec:
  replicas: 2
  leaderWorkerTemplate:
    size: 17
    leaderTemplate:
      metadata:
        labels:
          # Required for the webhook to inject the node selector
          tpu-provisioner.cloud.google.com/inject-slice-selector: "true"
        annotations:
          # TPU Topology
          cloud.google.com/gke-tpu-topology: "4x4x4"
      spec:
        containers:
        - name: leader
          image: nginx:latest
          resources:
            limits:
              google.com/tpu: "4"
        nodeSelector:
          # TPU Accelerator Type
          cloud.google.com/gke-tpu-accelerator: "tpu7x"
    workerTemplate:
      metadata:
        labels:
          # Required for the webhook to inject the node selector
          tpu-provisioner.cloud.google.com/inject-slice-selector: "true"
        annotations:
          # TPU Topology
          cloud.google.com/gke-tpu-topology: "4x4x8"
      spec:
        containers:
        - name: worker
          image: nginx:latest
          resources:
            limits:
              google.com/tpu: "4"
        nodeSelector:
          # TPU Accelerator Type
          cloud.google.com/gke-tpu-accelerator: "tpu7x"
