apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  annotations:
    tpu-provisioner.cloud.google.com/slice-selection: |
      {
        "workers": [["b000t4x4x4", "c000t4x4x4"],["d000t4x4x4", "e000t4x4x4"]]
      }
  creationTimestamp: "2026-02-09T21:49:45Z"
  finalizers:
  - tpu-provisioner.cloud.google.com/slice-cleanup
  generation: 2
  labels:
    tpu-provisioner.cloud.google.com/slice-autoprovisioning: async
  name: example-2
  namespace: default
  resourceVersion: "89007"
  uid: 214ec26c-08ed-4080-b692-4c753e565cab
spec:
  leaderWorkerTemplate:
    leaderTemplate:
      metadata:
        labels:
          kwok-simulated-job: "true"
      spec:
        containers:
        - image: nginx:latest
          name: leader
          resources: {}
    restartPolicy: RecreateGroupOnPodRestart
    size: 33
    workerTemplate:
      metadata:
        annotations:
          cloud.google.com/gke-tpu-topology: 4x4x8
        labels:
          kwok-simulated-job: "true"
          tpu-provisioner.cloud.google.com/inject-slice-selector: "true"
      spec:
        containers:
        - image: nginx:latest
          name: worker
          resources:
            limits:
              google.com/tpu: "4"
        nodeSelector:
          cloud.google.com/gke-tpu-accelerator: tpu7x
        tolerations:
        - effect: NoSchedule
          key: google.com/tpu
          operator: Exists
  networkConfig:
    subdomainPolicy: Shared
  replicas: 2
  rolloutStrategy:
    rollingUpdateConfiguration:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  startupPolicy: LeaderCreated
status:
  conditions:
  - lastTransitionTime: "2026-02-09T21:49:45Z"
    message: Replicas are progressing
    reason: GroupsProgressing
    status: "False"
    type: Progressing
  - lastTransitionTime: "2026-02-09T21:49:48Z"
    message: All replicas are ready
    reason: AllGroupsReady
    status: "True"
    type: Available
  hpaPodSelector: leaderworkerset.sigs.k8s.io/name=example-2,leaderworkerset.sigs.k8s.io/worker-index=0
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
