name: Unit tests

on: [pull_request]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      with:
        persist-credentials: false

    - name: Run build target
      run: make build

    - name: Run test target
      run: make test
